require 'shellwords'

task :default => ['webconsole:tests']

namespace :webconsole do

  task :tests => [:clean_up]

  task :test_webconsole do
    webconsole_gem_tests_file = File.join(File.dirname(__FILE__), "tc_webconsole.rb")
    ruby Shellwords.escape(webconsole_gem_tests_file)
  end

  task :clean_up => [:test_webconsole] do
    data_directory = File.join(File.dirname(__FILE__), "data")
    quit_applescript_file = File.join(data_directory, "quit.applescript")
    sh "osascript #{Shellwords.escape(quit_applescript_file)}"
  end

end