require 'shellwords'

task :default => ['wcirb:tests']

namespace :wcirb do
  
  task :tests => [:clean_up]

  task :test_controller do
    controller_tests_file = File.join(File.dirname(__FILE__), "tc_controller.rb")
    ruby Shellwords.escape(controller_tests_file)
  end

  task :test_bridge => [:test_controller] do
    bridge_tests_file = File.join(File.dirname(__FILE__), "tc_bridge.rb")
    ruby Shellwords.escape(bridge_tests_file)
  end

  task :test_wcirb => [:test_bridge] do
    wcirb_tests_file = File.join(File.dirname(__FILE__), "tc_wcirb.rb")
    ruby Shellwords.escape(wcirb_tests_file)
  end

  task :clean_up => [:test_wcirb] do
    quit_applescript_file = File.join(File.dirname(__FILE__), "applescript", "quit.applescript")
    sh "osascript #{Shellwords.escape(quit_applescript_file)}"
  end
end