TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_NAME = "withoutArguments"
TEST_JAVASCRIPT_FUNCTION_WITHOUT_ARGUMENTS_RESULT = "test"

TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_NAME = "withArguments"
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_ARGUMENTS = ["one", "two"]
TEST_JAVASCRIPT_FUNCTION_WITH_ARGUMENTS_RESULT = "onetwo"
