require 'shellwords'

task :default => ['wcack:clean_up']

namespace :wcack do
  WCACK_TESTS_DIRECTORY = File.expand_path(File.dirname(__FILE__))

  task :test_parser do
    PARSER_TESTS_FILE = File.join(WCACK_TESTS_DIRECTORY, "tc_parser.rb")
    ruby Shellwords.escape(PARSER_TESTS_FILE)
  end

  task :test_controller => [:test_parser] do
    CONTROLLER_TESTS_FILE = File.join(WCACK_TESTS_DIRECTORY, "tc_controller.rb")
    ruby Shellwords.escape(CONTROLLER_TESTS_FILE)
  end

  task :test_wcack => [:test_controller] do
    WCACK_TESTS_FILE = File.join(WCACK_TESTS_DIRECTORY, "tc_wcack.rb")
    ruby Shellwords.escape(WCACK_TESTS_FILE)
  end

  task :clean_up => [:test_wcack] do
    QUIT_APPLESCRIPT_FILE = File.join(WCACK_TESTS_DIRECTORY, "applescript", "quit.applescript")
    sh "osascript #{Shellwords.escape(QUIT_APPLESCRIPT_FILE)}"
  end
end