BUNDLE_PATHS = [
  "../../Web Console/Plugins/Shared Test Resources.wcplugin/Contents/Resources/plugin/Print.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Shared Test Resources.wcplugin/Contents/Resources/plugin/TestEnvironment.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Shared Test Resources.wcplugin/Contents/Resources/plugin/TestLog.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Node.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Markdown.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/IRB.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/HTML.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Coffee.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Search.wcplugin/Contents/Resources/",
  "../../Web Console/Plugins/Log.wcplugin/Contents/Resources/"
]

task :default => [:run]

task :run do
  BUNDLE_PATHS.each { |path|
    File.directory?(path) || abort("#{path} is not a directory")
    Dir.chdir(path) do
      directory = `pwd`
      puts directory
      Rake::Task[:update].invoke
      Rake::Task[:update].reenable
      Rake::Task[:install].reenable
    end
  }
end

task :install do |t, args|
  puts "INSTALL"
  sh "bundle install --standalone --clean --path bundle"
end

task :update => :install do |t, args|
  puts "UPDATE"
  sh "bundle update"
end
