PLUGIN_NAME_KEY = 'WC_PLUGIN_NAME'
WINDOW_ID_KEY = 'WC_WINDOW_ID'
SHARED_RESOURCES_PATH_KEY = 'WC_SHARED_RESOURCE_PATH'
SHARED_RESOURCES_URL_KEY = 'WC_SHARED_RESOURCE_URL'

TEST_PLUGIN_NAME = "TestEnvironment"