require 'shellwords'

TESTS_DIRECTORY = File.expand_path(File.dirname(__FILE__))

DATA_DIRECTORY = File.join(TESTS_DIRECTORY, "data")
QUIT_APPLESCRIPT_FILE = File.join(DATA_DIRECTORY, "quit.applescript")

XCODEBUILD_SCHEME = "Web Console"
XCODEBUILD_PROJECT_FILE = File.expand_path(File.join(TESTS_DIRECTORY, "../../Web Console/Web Console.xcodeproj"))

WEBCONSOLE_TESTS_FILE = File.join(TESTS_DIRECTORY, "tc_web_console.rb")
WEBCONSOLE_GEM_TESTS_FILE = File.join(TESTS_DIRECTORY, "../../Web Console/webconsole/test/tc_webconsole.rb")

task :default => [:clean_up]

task :test_xcunit do
  sh "xcodebuild test -scheme #{Shellwords.escape(XCODEBUILD_SCHEME)} -project #{Shellwords.escape(XCODEBUILD_PROJECT_FILE)}"
end

task :test_webconsole_gem => [:test_xcunit] do
  ruby Shellwords.escape(WEBCONSOLE_GEM_TESTS_FILE)
end

task :test_web_console => [:test_webconsole_gem] do
  ruby Shellwords.escape(WEBCONSOLE_TESTS_FILE)
end

task :clean_up => [:test_web_console] do
  sh "osascript #{Shellwords.escape(QUIT_APPLESCRIPT_FILE)}"
end