require 'shellwords'

WEBCONSOLE_TESTS_DIRECTORY = File.expand_path(File.dirname(__FILE__))
WCACK_TEST_RAKEFILE = File.expand_path(File.join(WEBCONSOLE_TESTS_DIRECTORY, "../..", "Web Console", "Ack", "wcack", "test", "Rakefile"))
import WCACK_TEST_RAKEFILE

task :default => ['webconsole:clean_up']

task :long => ['webconsole:test_web_console_long', 'webconsole:clean_up']
task :xcunit => ['webconsole:test_xcunit']

task :wcack => ['wcack:clean_up']

namespace :webconsole do

  task :test_xcunit do
    XCODEBUILD_SCHEME = "Web Console"
    XCODEBUILD_PROJECT_FILE = File.expand_path(File.join(WEBCONSOLE_TESTS_DIRECTORY, "../../Web Console/Web Console.xcodeproj"))
    sh "xcodebuild test -scheme #{Shellwords.escape(XCODEBUILD_SCHEME)} -project #{Shellwords.escape(XCODEBUILD_PROJECT_FILE)}"
  end

  task :test_webconsole_gem => [:test_xcunit] do
    WEBCONSOLE_GEM_TESTS_FILE = File.join(WEBCONSOLE_TESTS_DIRECTORY, "../../Web Console/webconsole/test/tc_webconsole.rb")
    ruby Shellwords.escape(WEBCONSOLE_GEM_TESTS_FILE)
  end

  task :test_web_console => [:test_webconsole_gem] do
    WEBCONSOLE_TESTS_FILE = File.join(WEBCONSOLE_TESTS_DIRECTORY, "tc_web_console.rb")
    ruby Shellwords.escape(WEBCONSOLE_TESTS_FILE)
  end

  task :clean_up => [:test_web_console] do
    DATA_DIRECTORY = File.join(WEBCONSOLE_TESTS_DIRECTORY, "data")
    QUIT_APPLESCRIPT_FILE = File.join(DATA_DIRECTORY, "quit.applescript")
    sh "osascript #{Shellwords.escape(QUIT_APPLESCRIPT_FILE)}"
  end

  # Long

  task :test_web_console_long => [:test_web_console] do
    WEBCONSOLE_TESTS_LONG_FILE = File.join(WEBCONSOLE_TESTS_DIRECTORY, "tc_web_console_long.rb")
    ruby Shellwords.escape(WEBCONSOLE_TESTS_LONG_FILE)
  end

end
