require 'shellwords'
require 'webconsole'
require WebConsole::shared_test_resource("ruby/test_constants")
require WebConsole::Tests::TEST_HELPER_FILE

task :default => ['webconsole:tests']

namespace :webconsole do

  task :tests => [:clean_up]

  task :test_view do
    view_tests_file = File.join(File.dirname(__FILE__), "tc_view.rb")
    ruby Shellwords.escape(view_tests_file)
  end

  task :test_window => [:test_view] do
    window_tests_file = File.join(File.dirname(__FILE__), "tc_window.rb")
    ruby Shellwords.escape(window_tests_file)
  end

  task :test_module => [:test_window] do
    module_tests_file = File.join(File.dirname(__FILE__), "tc_module.rb")
    ruby Shellwords.escape(module_tests_file)
  end

  task :clean_up => [:test_module] do
    WebConsole::Tests::Helper::quit
  end

end